export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1

# Ablation
# CUDA_VISIBLE_DEVICES=0 PORT=23455 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_SM/FOLD_0 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 model.panoptic_head.auxscaleloss=False --resume &
# CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_SM/FOLD_1 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 model.panoptic_head.auxscaleloss=False --resume &
# CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_SM/FOLD_2 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 model.panoptic_head.auxscaleloss=False --resume &
# CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_SM/FOLD_3 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 model.panoptic_head.auxscaleloss=False --resume &
# CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_SM/FOLD_4 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 model.panoptic_head.auxscaleloss=False --resume

# CUDA_VISIBLE_DEVICES=0 PORT=23455 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_CE/FOLD_0 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 --resume &
# CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_CE/FOLD_1 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 --resume &
# CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_CE/FOLD_2 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 --resume &
# CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_CE/FOLD_3 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 --resume &
# CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_wo_CE/FOLD_4 --cfg-options model.panoptic_head.loss_scale.loss_weight=0 --resume


# Clip
# CUDA_VISIBLE_DEVICES=0 PORT=23455 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_CLIP/FOLD_0 --cfg-options model.panoptic_head.clip_encoder.load_from="" --resume &
# CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_CLIP/FOLD_1 --cfg-options model.panoptic_head.clip_encoder.load_from="" --resume &
# CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_CLIP/FOLD_2 --cfg-options model.panoptic_head.clip_encoder.load_from="" --resume &
# CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_CLIP/FOLD_3 --cfg-options model.panoptic_head.clip_encoder.load_from="" --resume &
# CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_CLIP/FOLD_4 --cfg-options model.panoptic_head.clip_encoder.load_from="" --resume

# SEEM Tuning
# CUDA_VISIBLE_DEVICES=5 PORT=23455 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_0 --cfg-options model.panoptic_head.clip_encoder.Freeze=False --resume &
# CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_1 --cfg-options model.panoptic_head.clip_encoder.Freeze=False --resume &
# CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_2 --cfg-options model.panoptic_head.clip_encoder.Freeze=False --resume &
# CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_3 --cfg-options model.panoptic_head.clip_encoder.Freeze=False --resume &
# CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_4 --cfg-options model.panoptic_head.clip_encoder.Freeze=False --resume


# Plip
CUDA_VISIBLE_DEVICES=0 PORT=23455 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_PLIP/FOLD_0 --cfg-options model.panoptic_head.clip_encoder.tokenizer_type="path-clip" model.panoptic_head.clip_encoder.lang_encoder.PRETRAINED_TOKENIZER="/mnt/bn/hjj-humanseg-yg/SEEM_DATA/plip" model.panoptic_head.clip_encoder.lang_encoder.TOKENIZER="path-clip" --resume &
CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_PLIP/FOLD_1 --cfg-options model.panoptic_head.clip_encoder.tokenizer_type="path-clip" model.panoptic_head.clip_encoder.lang_encoder.PRETRAINED_TOKENIZER="/mnt/bn/hjj-humanseg-yg/SEEM_DATA/plip" model.panoptic_head.clip_encoder.lang_encoder.TOKENIZER="path-clip" --resume &
CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_PLIP/FOLD_2 --cfg-options model.panoptic_head.clip_encoder.tokenizer_type="path-clip" model.panoptic_head.clip_encoder.lang_encoder.PRETRAINED_TOKENIZER="/mnt/bn/hjj-humanseg-yg/SEEM_DATA/plip" model.panoptic_head.clip_encoder.lang_encoder.TOKENIZER="path-clip" --resume &
CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_PLIP/FOLD_3 --cfg-options model.panoptic_head.clip_encoder.tokenizer_type="path-clip" model.panoptic_head.clip_encoder.lang_encoder.PRETRAINED_TOKENIZER="/mnt/bn/hjj-humanseg-yg/SEEM_DATA/plip" model.panoptic_head.clip_encoder.lang_encoder.TOKENIZER="path-clip" --resume &
CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_PLIP/FOLD_4 --cfg-options model.panoptic_head.clip_encoder.tokenizer_type="path-clip" model.panoptic_head.clip_encoder.lang_encoder.PRETRAINED_TOKENIZER="/mnt/bn/hjj-humanseg-yg/SEEM_DATA/plip" model.panoptic_head.clip_encoder.lang_encoder.TOKENIZER="path-clip" --resume




# CUDA_VISIBLE_DEVICES=0,1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_Mask2Former/SwinB_FOLD_1.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Mask2Former/FOLD_1 --resume &
# CUDA_VISIBLE_DEVICES=2,3 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_Mask2Former/SwinB_FOLD_2.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Mask2Former/FOLD_2 --resume &
# CUDA_VISIBLE_DEVICES=4,5 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_Mask2Former/SwinB_FOLD_3.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Mask2Former/FOLD_3 --resume &
# CUDA_VISIBLE_DEVICES=6,7 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_Mask2Former/SwinB_FOLD_4.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Mask2Former/FOLD_4 --resume &

# CUDA_VISIBLE_DEVICES=0 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_0.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer/FOLD_1 --resume &
# CUDA_VISIBLE_DEVICES=1 PORT=23456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer/FOLD_1 --resume &
# CUDA_VISIBLE_DEVICES=2 PORT=23457 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_2.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer/FOLD_2 --resume &
# CUDA_VISIBLE_DEVICES=3 PORT=23458 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_3.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer/FOLD_3 --resume &
# CUDA_VISIBLE_DEVICES=4 PORT=23459 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_4.py 2 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer/FOLD_4 --resume &



# source /mnt/bn/hjj-humanseg-yg/miniconda3/bin/activate && conda activate mmdetection && cd /mnt/bn/hjj-humanseg-yg/UniScaleFormer/Mask2Former/mmdetection/ && CUDA_VISIBLE_DEVICES=6 PORT=27456 ./tools/dist_train.sh projects/MultiScaleMask2Former/configs/KFOLD_UniScaleFormer/SwinB_FOLD_1.py 1 --work-dir=/mnt/bn/hjj-humanseg-yg/UniScaleFormer/RESULTS/Ablation/UniScaleFormer_TE_SEEM_Tuning/FOLD_1 --cfg-options model.panoptic_head.clip_encoder.Freeze=False  model.panoptic_head.pixel_decoder.encoder.num_layers=3 model.panoptic_head.transformer_decoder.num_layers=3 --resume 